[features]
seeds = false
skip-lint = false
[programs.devnet]
decentralized_stock_exchange = "3Hx4VgF8rWqUanwb879HdGU9q6ptskQtyyjGqc25ojec"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/RegisterEnterprise.ts"
